# Generated by Django 3.2.12 on 2022-04-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_five',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_three',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
